spring.application.name=JuventudxTemixco

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Leer los archivos multipart de forma temprana
spring.servlet.multipart.resolve-lazily=true

#Security
jwt.expiration-ms = 86400000
jwt.secret=${JWT_SECRET}


# Configuración del servidor de correos
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bahenaalberto35@gmail.com

spring.mail.password=${PASSWORD_APPLICATION}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Configuración para donaciones Paypal
paypal.client-id=${LIVE_ID}
paypal.client-secret=${LIVE_SECRET}
paypal.base-url=https://api-m.paypal.com
